const slides=[
 {label:'KIRISH',title:'Darsni rejalashtirish — natijani oldindan loyihalash',text:'Ta’lim texnologiyalariga asoslangan dars rejasi o‘qituvchining maqsad, faoliyat, metod, vosita va kutiladigan natijalarni oldindan tizimlashtirishiga xizmat qiladi.',actions:[['Maqsad','Dars yakunida o‘quvchi nimani bilishi yoki bajara olishi aniq ifodalanadi.'],['Jarayon','Maqsadga olib boradigan o‘quv faoliyati bosqichma-bosqich belgilanadi.'],['Natija','Baholash orqali kutilgan natijaga erishilgan-erishilmaganligi aniqlanadi.']]},
 {label:'01 / MUAMMO',title:'Nega darsni oldindan loyihalash kerak?',text:'Rejasiz darsda mazmun, vaqt va faoliyatlar o‘rtasidagi bog‘liqlik zaiflashishi mumkin. Loyihalash esa darsning mantiqiy ketma-ketligini oldindan ko‘rishga yordam beradi.',actions:[['Muammo','Vaqt noto‘g‘ri taqsimlansa, asosiy faoliyatga yetarli vaqt qolmasligi mumkin.'],['Yechim','Maqsad, metod va baholashni bir tizim sifatida rejalashtirish.'],['Nazorat','Har bir bosqich uchun kuzatiladigan natijani belgilash.']]},
 {label:'02 / TUZILMA',title:'Yaxshi dars rejasining uch tayanchi',text:'Samarali reja maqsad, jarayon va natijani yagona mantiqiy zanjirga birlashtiradi.',actions:[['Maqsad','Aniq, o‘lchanadigan va dars mazmuniga mos bo‘lishi kerak.'],['Jarayon','O‘quvchi faoliyati va o‘qituvchi faoliyati o‘zaro bog‘lanadi.'],['Natija','Bilim, ko‘nikma yoki kompetensiya shaklida ifodalanadi.']]},
 {label:'03 / METODLAR',title:'Dars metodini maqsadga mos tanlash',text:'Metod darsning maqsadi va o‘quvchi faoliyatiga mos tanlanadi. Bitta metod barcha vaziyat uchun universal emas.',actions:[['Muammoli ta’lim','Muammoli vaziyat orqali fikrlash va yechim izlashni faollashtiradi.'],['Hamkorlikdagi ta’lim','Guruh va juftlikdagi faoliyat orqali muloqot hamda hamkorlikni rivojlantiradi.'],['Loyihaviy ta’lim','Aniq mahsulot yoki yechim yaratishga yo‘naltirilgan uzoqroq faoliyat.'],['Amaliy ta’lim','Nazariy bilimni real topshiriq va amaliy harakat bilan bog‘laydi.']]},
 {label:'04 / KONSTRUKTOR',title:'Darsni bosqichma-bosqich qurish',text:'Darsni loyihalashda bosqichlar o‘zaro bog‘lanadi: motivatsiya, yangi bilim, amaliy faoliyat, mustahkamlash va baholash.',actions:[['Kirish','Mavzuga qiziqish va avvalgi bilimlarni faollashtirish.'],['Asosiy qism','Yangi bilimni tushuntirish va faol o‘quv topshirig‘i.'],['Amaliyot','O‘quvchi bilimni amalda qo‘llaydi.'],['Baholash','Natija mezon asosida tekshiriladi.']]},
 {label:'05 / TEXNOLOGIYA',title:'Metod, vosita va baholashni uyg‘unlashtirish',text:'Ta’lim texnologiyasi faqat texnik vosita emas. U maqsad, metod, o‘quv faoliyati, vosita va baholashning o‘zaro uyg‘un tizimidir.',actions:[['Metod','Qanday o‘qitish?'],['Vosita','Qaysi resursdan foydalanish?'],['Faoliyat','O‘quvchi nima qiladi?'],['Baholash','Natijani qanday aniqlaymiz?']]},
 {label:'06 / YAKUNIY MODEL',title:'Tayyor dars rejasini tekshirish',text:'Yakuniy reja mantiqiy zanjir sifatida tekshiriladi: maqsad → faoliyat → metod → vosita → baholash → natija.',actions:[['1. Maqsad','Maqsad dars mazmuni va kutilgan natijaga mosmi?'],['2. Faoliyat','O‘quvchi darsda faol harakat qiladimi?'],['3. Baholash','Baholash aynan belgilangan natijani o‘lchaydimi?']]}
];
const bank=[
['Dars rejasining asosiy vazifasi nima?','Dars jarayonini oldindan tizimlashtirish','Faqat uy vazifasini yozish','Faqat vaqtni belgilash','Faqat baho qo‘yish','easy'],
['Dars maqsadi nimani ko‘rsatadi?','Kutiladigan o‘quv natijasini','Faqat mavzu nomini','Faqat dars vaqtini','Faqat jihozlarni','easy'],
['Ta’lim metodini tanlashda nima muhim?','Maqsad va o‘quv faoliyatiga moslik','Faqat o‘qituvchining odati','Faqat sinf xonasi','Faqat dars davomiyligi','easy'],
['Baholashning asosiy vazifasi nima?','Kutilgan natijaga erishishni aniqlash','Darsni qisqartirish','Mavzuni o‘zgartirish','Uy vazifasini bekor qilish','easy'],
['Hamkorlikdagi ta’lim nimaga tayanadi?','Birgalikdagi faoliyat va muloqotga','Faqat individual ishlashga','Faqat ma’ruzaga','Faqat testga','easy'],
['Muammoli ta’limning markazida nima turadi?','Muammoli vaziyat va yechim izlash','Faqat yodlash','Faqat ko‘chirish','Faqat nazorat ishi','easy'],
['Loyihaviy ta’limning asosiy belgisi?','Aniq mahsulot yoki yechim yaratish','Faqat og‘zaki so‘rov','Faqat matn yodlash','Faqat diktant','easy'],
['Amaliy ta’lim nimani kuchaytiradi?','Bilimni amalda qo‘llashni','Faqat nazariy yodlashni','Faqat yozma nazoratni','Faqat tinglashni','easy'],
['Dars rejasidagi bosqichlar qanday bog‘lanadi?','Maqsad va natija mantiqi orqali','Tasodifiy tartibda','Faqat vaqt orqali','Faqat mavzu nomi orqali','easy'],
['Yaxshi dars rejasida nima bo‘lishi kerak?','Maqsad, faoliyat, metod va baholash uyg‘unligi','Faqat mavzu','Faqat topshiriqlar','Faqat baholar','easy'],
['SMART maqsadning foydasi nimada?','Maqsadni aniq va o‘lchanadigan qilishda','Darsni bezashda','Faqat vaqtni uzaytirishda','Faqat nazoratni bekor qilishda','medium'],
['Maqsad va baholash o‘rtasidagi bog‘liqlik qanday bo‘lishi kerak?','Baholash maqsadga erishishni o‘lchashi kerak','Ular bog‘liq bo‘lmasligi kerak','Faqat baho muhim','Faqat metod muhim','medium'],
['O‘quvchi faoliyatini markazga qo‘yish nimani anglatadi?','O‘quvchining faol ishtirokini loyihalash','Faqat o‘qituvchini gapirtirish','Faqat yozdirish','Faqat nazorat qilish','medium'],
['Dars metodini noto‘g‘ri tanlash nimaga olib kelishi mumkin?','Maqsad va faoliyat nomuvofiqligiga','Natijaning avtomatik oshishiga','Vaqtning ko‘payishiga','Baholashning yo‘qolishiga','medium'],
['Formativ baholashning xususiyati?','Jarayon davomida qayta aloqa berish','Faqat yakuniy baho qo‘yish','Faqat sertifikat berish','Faqat davomat olish','medium'],
['Dars bosqichlarini rejalashda vaqt nima uchun kerak?','Faoliyatlarni real vaqtga mos taqsimlash uchun','Faqat jadvalni bezash uchun','Faqat baho uchun','Faqat mavzu nomi uchun','medium'],
['Interfaol metodlarning umumiy xususiyati?','O‘quvchini faol fikrlash va ishtirokka jalb qilish','O‘quvchini faqat tinglovchiga aylantirish','Faqat yodlash','Faqat o‘qituvchi faoliyati','medium'],
['Ta’lim texnologiyasi tushunchasi nimani qamrab oladi?','Maqsad, mazmun, metod, faoliyat, vosita va baholash tizimini','Faqat kompyuterni','Faqat internetni','Faqat darslikni','medium'],
['Kutiladigan natija qanday ifodalansa qulay?','Kuzatiladigan va baholanadigan harakat orqali','Juda umumiy ibora bilan','Faqat mavzu nomi bilan','Faqat o‘qituvchi harakati bilan','medium'],
['Dars rejasini tekshirishning muhim mezoni?','Maqsad-faoliyat-baholash mosligi','Faqat dizayn','Faqat matn hajmi','Faqat dars davomiyligi','medium'],
['Darsni loyihalashda konstruktiv moslik nimani anglatadi?','Maqsad, faoliyat va baholashning bir-birini qo‘llab-quvvatlashini','Faqat ko‘p topshiriq berishni','Faqat texnologik qurilma ishlatishni','Faqat murakkab test tuzishni','hard'],
['Agar maqsad “amaliy ko‘nikma” bo‘lsa, baholashga qaysi topshiriq mosroq?','Amaliy bajarish va mezon asosida kuzatish','Faqat ta’rif yodlash','Faqat tanlash testi','Faqat matn ko‘chirish','hard'],
['Ta’lim texnologiyasini tanlashda eng muhim boshlang‘ich nuqta nima?','Kutilayotgan o‘quv natijasi','Mavjud texnika soni','Slayd dizayni','Darslik hajmi','hard'],
['Bir metod turli guruhlarda turlicha natija berishi nimani ko‘rsatadi?','Kontekst va o‘quvchi xususiyatlarini hisobga olish zarurligini','Metodlar keraksizligini','Baholash kerak emasligini','Reja tuzish shart emasligini','hard'],
['Dars rejasida “faoliyat” va “natija”ni ajratish nega muhim?','Bajarilgan ish bilan erishilgan o‘quv natijasini farqlash uchun','Faqat matnni ko‘paytirish uchun','Faqat vaqtni hisoblash uchun','Faqat dizayn uchun','hard'],
['Teskari dizayn yondashuvida rejalash qayerdan boshlanadi?','Kutiladigan natija va baholashdan','Faqat jihozlardan','Faqat kirish qismidan','Faqat uy vazifasidan','hard'],
['Metod va vosita o‘rtasidagi farq nima?','Metod — o‘qitish usuli, vosita — jarayonni qo‘llab-quvvatlovchi resurs','Ikkalasi ham bir xil tushuncha','Vosita maqsadning o‘zi','Metod faqat texnika','hard'],
['Yakuniy dars rejasida baholash mezonlari bo‘lmasa, qaysi muammo kuchayadi?','Natijani obyektiv aniqlash qiyinlashadi','Mavzu avtomatik o‘zgaradi','Vaqt avtomatik tejaladi','Metod o‘z-o‘zidan tanlanadi','hard'],
['Darsning barcha komponentlari bir-biriga mos bo‘lsa, qanday tizim hosil bo‘ladi?','Mantiqiy va yaxlit ta’lim jarayoni','Faqat nazorat tizimi','Faqat texnik tizim','Faqat ma’ruza tizimi','hard'],
['Professional dars loyihasining yakuniy tekshiruvida nimaga qaraladi?','Maqsad, faoliyat, metod, vosita, baholash va natijaning uyg‘unligiga','Faqat slayd soniga','Faqat ranglarga','Faqat savollar soniga','hard']
].map(x=>({q:x[0],correct:x[1],options:[x[1],x[2],x[3],x[4]],level:x[5]}));

const $=s=>document.querySelector(s);let slideIndex=0,questions=[],qIndex=0,selected=null,correct=0,timerId=null,timeLeft=30;
function showScreen(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));$('#'+id).classList.add('active');window.scrollTo({top:0,behavior:'smooth'});}
function renderSlide(){const s=slides[slideIndex];$('#slideTitle').textContent=s.title;$('#slideLabel').textContent=s.label;$('#slideText').textContent=s.text;$('#slideCount').textContent=String(slideIndex+1).padStart(2,'0')+' / 07';$('#sideNumber').textContent=String(slideIndex+1).padStart(2,'0');$('#lessonProgress').style.width=((slideIndex+1)/slides.length*100)+'%';$('#prevBtn').disabled=slideIndex===0;$('#nextBtn').textContent=slideIndex===slides.length-1?'TESTGA O‘TISH':'KEYINGI →';$('#slideInfo').classList.add('hidden');$('#slideInfo').textContent='';const box=$('#slideActions');box.innerHTML='';s.actions.forEach((a,i)=>{const b=document.createElement('button');b.className='action-btn';b.textContent=a[0];b.addEventListener('click',()=>{box.querySelectorAll('.action-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#slideInfo').textContent=a[1];$('#slideInfo').classList.remove('hidden')});box.appendChild(b)})}
function startLesson(){slideIndex=0;renderSlide();showScreen('lesson')}
function nextSlide(){if(slideIndex<slides.length-1){slideIndex++;renderSlide()}else startTest()}
function prevSlide(){if(slideIndex>0){slideIndex--;renderSlide()}}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function startTest(){clearInterval(timerId);const e=shuffle(bank.filter(x=>x.level==='easy')).slice(0,3),m=shuffle(bank.filter(x=>x.level==='medium')).slice(0,4),h=shuffle(bank.filter(x=>x.level==='hard')).slice(0,3);questions=shuffle([...e,...m,...h]);qIndex=0;correct=0;showScreen('test');loadQuestion()}
function loadQuestion(){selected=null;timeLeft=30;$('#timer').textContent=timeLeft;$('#questionNo').textContent=qIndex+1;$('#testProgress').style.width=(qIndex/questions.length*100)+'%';const q=questions[qIndex];$('#questionText').textContent=q.q;$('#difficulty').textContent=q.level==='easy'?'OSON':q.level==='medium'?'O‘RTA':'MURAKKAB';$('#answerState').textContent='Variantni tanlang';$('#confirmBtn').disabled=true;const box=$('#answers');box.innerHTML='';shuffle(q.options).forEach((text,i)=>{const b=document.createElement('button');b.className='answer';const key=document.createElement('span');key.className='answer-key';key.textContent=String.fromCharCode(65+i);const label=document.createElement('span');label.textContent=text;b.append(key,label);b.addEventListener('click',()=>{box.querySelectorAll('.answer').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');selected=text;$('#answerState').textContent='Tanlandi';$('#confirmBtn').disabled=false});box.appendChild(b)});clearInterval(timerId);timerId=setInterval(()=>{timeLeft--;$('#timer').textContent=timeLeft;if(timeLeft<=0){clearInterval(timerId);confirmAnswer(true)}},1000)}
function confirmAnswer(timeout=false){if(!selected&&!timeout)return;clearInterval(timerId);if(selected===questions[qIndex].correct)correct++;qIndex++;if(qIndex<questions.length){setTimeout(loadQuestion,timeout?250:180)}else setTimeout(showResult,180)}
function showResult(){showScreen('result');const total=questions.length,wrong=total-correct,percent=Math.round(correct/total*100);$('#score').textContent=percent+'%';$('#correctCount').textContent=correct;$('#wrongCount').textContent=wrong;$('#resultTotal').textContent=total;$('#resultText').textContent=percent>=80?'Mavzu bo‘yicha bilimlar yaxshi o‘zlashtirilgan.':percent>=60?'Asosiy tushunchalar o‘zlashtirilgan, ayrim qismlarni takrorlash foydali.':'Nazariy bloklarni qayta ko‘rib chiqish tavsiya etiladi.'}
$('#startLessonBtn').addEventListener('click',startLesson);$('#startTestBtn').addEventListener('click',startTest);$('#nextBtn').addEventListener('click',nextSlide);$('#prevBtn').addEventListener('click',prevSlide);$('#confirmBtn').addEventListener('click',()=>confirmAnswer(false));$('#retryBtn').addEventListener('click',startTest);$('#homeBtn').addEventListener('click',()=>showScreen('home'));renderSlide();
